
spring:
  cloud:
    stream:
      kafka:
        default:
          producer:
            recordMetadataChannel: kafkaAckListener
      binders:
        kafka-binder:
          type: kafka
      function:
        bindings:
          thingSupplier-out-0: things-out
      bindings:
        things-out:
          content-type: application/thing
          destination: thing-topic
    function:
      definition: thingSupplier;